name: Deploy website

on:
  push:
    branches:
      - 'main'
  workflow_dispatch:
  schedule:
    - cron:  '15 1 * * 1-5' # Mon-Fri, 1:15AM UTC / 7PM CST

jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    permissions: {}
    steps:
      - uses: actions/checkout@900f2210b1d28bbbd0bd22d17926b9e224e8f231 # 2026-05-21
        with:
          persist-credentials: false
      - uses: superfly/flyctl-actions/setup-flyctl@ed8efb33836e8b2096c7fd3ba1c8afe303ebbff1 # 2026-05-21
      - run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
